import Head from 'next/head'
import Image from 'next/image'
import Atributies from '../component/atributies/Atributies'
import Currency from '../component/currency-list/Currency'
import Footer from '../component/footer/Footer'
import Friends from '../component/friends/Friends'
import Intro from '../component/intro/Intro'
import { Navbar } from '../component/navbar/Navbar'
import QuickAccess from '../component/qiuick-access/QuickAccess'
import Questions from '../component/questions/Questions'
export default function Home() {
  return (
    <>
    
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
       
          <Intro />
       <Currency/>
       <Atributies/>
       <QuickAccess/>
       <Questions/>
       <Friends/>
       <Footer/>
    </main>
    </>
  )
}
